import type { Metadata } from "next";
import "./globals.css";
import AnimationInitializer from "./components/animation-initializer";
import { interTight } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${interTight.variable} font-sans`}>
        <AnimationInitializer />
        {children}
      </body>
    </html>
  );
}
